# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/ktexteditor': '@stable'
    'frameworks/kitemmodels': '@stable'
    'kdevelop/kdevelop': '@stable'
    'kdevelop/kdev-executebrowser': '@stable'
