[Desktop Entry]
Type=Service
Exec=blubb
Comment=This plugin provides a frontend for XDebug
Comment[ca]=Aquest connector proveeix d'un frontal pel XDebug
Comment[ca@valencia]=Este connector proveeix d'un frontal pel XDebug
Comment[de]=Dieses Modul stellt eine Oberfläche für XDebug zur Verfügung
Comment[es]=Este complemento proporciona una interfaz para XDebug
Comment[fr]=Ce module externe fournit une interface pour XDebug
Comment[ga]=Soláthraíonn an breiseán seo comhéadan ar XDebug
Comment[hu]=Ez a bővítmény egy előtétprogramot szolgáltat az XDebug-hoz
Comment[it]=Questa estensione fornisce un interfaccia per XDebug
Comment[nl]=Deze plugin levert een frontend voor XDebug
Comment[pl]=Wtyczka ta dostarcza interfejs dla XDebug
Comment[pt]=Este 'plugin' oferece uma interface para o XDebug
Comment[pt_BR]=Este plugin fornece uma interface para o XDebug
Comment[sk]=Tento plugin poskytuje rozhranie pre XDebug
Comment[sv]=Insticksprogrammet tillhandahåller ett gränssnitt för Xdebug
Comment[tr]=Bu eklenti XDebug'a önuç sağlar
Comment[uk]=Цей додаток є оболонкою до XDebug
Comment[x-test]=xxThis plugin provides a frontend for XDebugxx
Name=XDebug Support
Name[ca]=Implementació per a XDebug
Name[ca@valencia]=Implementació per a XDebug
Name[cs]=Podpora XDebug
Name[de]=XDebug-Unterstützung
Name[es]=Implementación de XDebug
Name[fr]=Prise en charge de XDebug
Name[ga]=Tacaíocht XDebug
Name[gl]=Compatibilidade con XDebug
Name[hu]=XDebug támogatás
Name[it]=Supporto XDebug
Name[nl]=Ondersteuning van XDebug
Name[pl]=Obsługa XDebug
Name[pt]=Suporte para o XDebug
Name[pt_BR]=Suporte ao XDebug
Name[sk]=Podpora XDebug
Name[sv]=Stöd för Xdebug
Name[tr]=XDebug Desteği
Name[uk]=Підтримка XDebug
Name[x-test]=xxXDebug Supportxx
GenericName=Debugger Frontend
GenericName[bs]=Korisničko okruženje za ispravljač grešaka
GenericName[ca]=Frontal del depurador
GenericName[ca@valencia]=Frontal del depurador
GenericName[cs]=Rozhraní pro ladicí nástroj
GenericName[de]=Debugger-Oberfläche
GenericName[es]=Interfaz del depurador
GenericName[fr]=Interface de débogueur
GenericName[ga]=Comhéadan Dífhabhtóra
GenericName[hu]=Hibakereső előtétprogram
GenericName[it]=Interfaccia al debugger
GenericName[nl]=Frontend voor debugger
GenericName[pl]=Nakładka graficzna debuggera
GenericName[pt]=Interface do Depurador
GenericName[pt_BR]=Interface do depurador
GenericName[sk]=Rozhranie debuggera
GenericName[sv]=Avlusningsgränssnitt
GenericName[tr]=Hata Çözücü Ön Ucu
GenericName[ug]=سازلىغۇچ ئالدى ئۇچى
GenericName[uk]=Клієнтська програма зневадника
GenericName[x-test]=xxDebugger Frontendxx

Icon=debugger
X-KDE-Library=kdevxdebug
X-KDevelop-Category=Global
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDE-PluginInfo-Name=kdevxdebug
X-KDE-PluginInfo-License=GPL
ServiceTypes=KDevelop/Plugin
X-KDevelop-Interfaces=org.kdevelop.IRunProvider
X-KDevelop-Mode=GUI
