// THIS FILE IS GENERATED
// WARNING! All changes made in this file will be lost!
#ifndef KDEVXDEBUG_VERSION_H
#define KDEVXDEBUG_VERSION_H

#include <kdeversion.h>

#define KDEVXDEBUG_MAJOR_VERSION @VERSION_MAJOR@
#define KDEVXDEBUG_MINOR_VERSION @VERSION_MINOR@
#define KDEVXDEBUG_PATCH_VERSION @VERSION_PATCH@

#define KDEVXDEBUG_VERSION_STR "@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_PATCH@"

#define KDEVXDEBUG_VERSION KDE_MAKE_VERSION(@VERSION_MAJOR@, @VERSION_MINOR@, @VERSION_PATCH@)

#endif
