// THIS FILE IS GENERATED
// WARNING! All changes made in this file will be lost!
#ifndef KDEVXDEBUG_VERSION_H
#define KDEVXDEBUG_VERSION_H

#include <kdeversion.h>

#define KDEVXDEBUG_MAJOR_VERSION @KDEVXDEBUG_VERSION_MAJOR@
#define KDEVXDEBUG_MINOR_VERSION @KDEVXDEBUG_VERSION_MINOR@
#define KDEVXDEBUG_PATCH_VERSION @KDEVXDEBUG_VERSION_PATCH@

#define KDEVXDEBUG_VERSION_STR "@KDEVXDEBUG_VERSION_MAJOR@.@KDEVXDEBUG_VERSION_MINOR@.@KDEVXDEBUG_VERSION_PATCH@"

#define KDEVXDEBUG_VERSION KDE_MAKE_VERSION(@KDEVXDEBUG_VERSION_MAJOR@, @KDEVXDEBUG_VERSION_MINOR@, @KDEVXDEBUG_VERSION_PATCH@)

#endif
